version: '3.8'
services:
  db:
    image: postgis/postgis:13-3.5
    container_name: postgis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydata
    ports: 
      - '5432:5432'
  web:
    build: .
    command: sh -c "sleep 7 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api 
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db