services:
  db:
    image: postgis/postgis:13-3.5
    container_name: lolkek
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydata
    ports: 
      - '5432:5432'
  web:
    build: .
    command: sh -c "sleep 7 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/api 
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 'django-insecure-zu!g21+53-qxbsg7&44+-$%m#$78qc$*+++k%8kb7!iwd9#j%w'
      POSTGRES_DB: mydata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      DB_HOST: db
    depends_on:
      - db